# SPDX-FileCopyrightText: 2025 aesc silicon
#
# SPDX-License-Identifier: Apache-2.0

Comp:
  index: 22
  type: 0
  z: -0.3  # Estimated value
  height: 0.25
Nwell:
  index: 21
  type: 0
  z: -0.3  # Estimated value
  height: 0.20
Poly2:
  index: 30
  type: 0
  z: -0.2
  height: 0.2
Contact:
  index: 33
  type: 0
  z: 0.0
  height: 0.7
Metal1:
  index: 34
  type: 0
  z: 0.7
  height: 0.55
Via1:
  index: 35
  type: 0
  z: 1.25
  height: 0.6
Metal2:
  index: 36
  type: 0
  z: 1.85
  height: 0.55
Via2:
  index: 38
  type: 0
  z: 2.4
  height: 0.9
Metal3:
  index: 42
  type: 0
  z: 3.3
  height: 0.55
Via3:
  index: 40
  type: 0
  z: 3.85
  height: 0.6
Metal4:
  index: 46
  type: 0
  z: 4.45
  height: 0.55
Via4:
  index: 41
  type: 0
  z: 5
  height: 0.6
Metal5:
  index: 81
  type: 0
  z: 5.6
  height: 0.55
Via5:
  index: 82
  type: 0
  z: 6.15
  height: 0.6
MetalTop:
  index: 53
  type: 0
  z: 6.75
  height: 0.69
