# SPDX-FileCopyrightText: 2025 aesc silicon
#
# SPDX-License-Identifier: Apache-2.0

nwell:
  index: 64
  type: 20
  z: -0.24
  height: 0.14
diff:
  index: 65
  type: 20
  z: -0.5
  height: 0.6
poly:
  index: 66
  type: 20
  z: 0
  height: 0.2
licon:
  index: 66
  type: 44
  z: 0
  height: 0.94
li1:
  index: 67
  type: 20
  z: 0.94
  height: 0.1
mcon:
  index: 67
  type: 44
  z: 1.04
  height: 0.34
met1:
  index: 68
  type: 20
  z: 1.38
  height: 0.36
via:
  index: 68
  type: 44
  z: 1.74
  height: 0.27
met2:
  index: 69
  type: 20
  z: 2.01
  height: 0.36
via2:
  index: 69
  type: 44
  z: 2.37
  height: 0.42
met3:
  index: 70
  type: 20
  z: 2.79
  height: 0.85
via3:
  index: 70
  type: 44
  z: 3.64
  height: 0.39
met4:
  index: 71
  type: 20
  z: 4.03
  height: 0.85
via4:
  index: 71
  type: 44
  z: 4.88
  height: 0.50
met5:
  index: 72
  type: 20
  z: 5.38
  height: 1.26
